import { boolean, check, integer, jsonb, pgTable, text, timestamp, uuid } from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";

export const users = pgTable("users", { id: uuid("id").primaryKey(), email: text("email").notNull().unique(), createdAt: timestamp("created_at").defaultNow().notNull() });
export const googleCredentials = pgTable("google_credentials", { id: uuid("id").primaryKey(), userId: uuid("user_id").notNull(), subject: text("subject").notNull(), encryptedRefreshToken: text("encrypted_refresh_token").notNull(), scopes: text("scopes").array().notNull(), expiresAt: timestamp("expires_at"), revokedAt: timestamp("revoked_at") });
export const activities = pgTable("activities", { id: uuid("id").primaryKey(), userId: uuid("user_id").notNull(), name: text("name").notNull(), normalizedName: text("normalized_name").notNull(), lastUsedAt: timestamp("last_used_at").notNull(), useCount: integer("use_count").notNull().default(0) });
export const timerSessions = pgTable("timer_sessions", { id: uuid("id").primaryKey(), userId: uuid("user_id").notNull(), activityId: uuid("activity_id").notNull(), startedAt: timestamp("started_at").notNull(), accumulatedSeconds: integer("accumulated_seconds").notNull().default(0), pausedAt: timestamp("paused_at"), state: text("state").notNull() });
export const sessionRecords = pgTable("session_records", { id: uuid("id").primaryKey(), userId: uuid("user_id").notNull(), activityId: uuid("activity_id").notNull(), activityName: text("activity_name").notNull(), status: text("status").notNull(), startedAt: timestamp("started_at").notNull(), endedAt: timestamp("ended_at").notNull(), durationSeconds: integer("duration_seconds").notNull(), calendarEligible: boolean("calendar_eligible").notNull().default(true), metadata: jsonb("metadata") }, (table) => [check("session_record_nonnegative_duration", sql`${table.durationSeconds} >= 0`), check("session_record_time_order", sql`${table.endedAt} >= ${table.startedAt}`)]);
export const outboxOperations = pgTable("outbox_operations", { id: uuid("id").primaryKey(), idempotencyKey: text("idempotency_key").notNull().unique(), type: text("type").notNull(), payload: jsonb("payload").notNull(), state: text("state").notNull(), attempts: integer("attempts").notNull().default(0) });
