import { randomUUID } from "node:crypto";
import { AppError } from "@/lib/errors";
import { secondsBetween } from "@/lib/time";
import type { Activity, MemoryRepository, Record, Timer } from "@/server/db/repositories";
export class TimerService {
  constructor(private readonly db: MemoryRepository, private readonly now = () => new Date()) {}
  start(userId: string, name: string) { const clean = name.trim(); if (!clean) throw new AppError("INVALID_NAME", "Activity name is required"); const normalizedName = clean.toLocaleLowerCase(); let activity = this.db.activities.find((item) => item.userId === userId && item.normalizedName === normalizedName); if (!activity) { activity = { id: randomUUID(), userId, name: clean, normalizedName, lastUsedAt: this.now(), useCount: 0 }; this.db.activities.push(activity); } activity.lastUsedAt = this.now(); activity.useCount += 1; const timer: Timer = { id: randomUUID(), userId, activityId: activity.id, startedAt: this.now(), accumulatedSeconds: 0, state: "RUNNING" }; this.db.timers.set(timer.id, timer); return timer; }
  get(id: string) { const timer = this.db.timers.get(id); if (!timer) throw new AppError("TIMER_NOT_FOUND", "Timer was not found", 404); return timer; }
  pause(id: string) { const timer = this.get(id); if (timer.state !== "RUNNING") throw new AppError("INVALID_STATE", "Only a running timer can pause"); timer.accumulatedSeconds += secondsBetween(timer.startedAt, this.now()); timer.pausedAt = this.now(); timer.state = "PAUSED"; return timer; }
  resume(id: string) { const timer = this.get(id); if (timer.state !== "PAUSED") throw new AppError("INVALID_STATE", "Only a paused timer can resume"); timer.startedAt = this.now(); timer.pausedAt = undefined; timer.state = "RUNNING"; return timer; }
  complete(id: string): Record { const timer = this.get(id); if (timer.state === "RUNNING") timer.accumulatedSeconds += secondsBetween(timer.startedAt, this.now()); if (timer.state !== "RUNNING" && timer.state !== "PAUSED") throw new AppError("INVALID_STATE", "Timer is already finalized"); const activity = this.db.activities.find((item) => item.id === timer.activityId)!; const endTime = this.now(); const record: Record = { id: randomUUID(), activityId: activity.id, activityName: activity.name, startTime: timer.startedAt, endTime, durationSeconds: Math.max(0, timer.accumulatedSeconds), status: "COMPLETED" }; timer.state = "COMPLETED"; this.db.records.push(record); return record; }
  cancel(id: string) { const timer = this.get(id); if (timer.state === "COMPLETED" || timer.state === "CANCELLED") throw new AppError("INVALID_STATE", "Timer is already finalized"); timer.state = "CANCELLED"; return timer; }
  recent(userId: string): Activity[] { return this.db.activities.filter((item) => item.userId === userId).sort((a, b) => b.lastUsedAt.getTime() - a.lastUsedAt.getTime()).slice(0, 8); }
}
